name: Integration Tests
run-name: Integration Tests

on:
  # build on pushes to release brannches
  push:
    branches:
      - 'mps/20**'

  # build on new PRs
  pull_request:

  # allow manual execution just in case
  workflow_dispatch:

jobs:
  runIntegrationTests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-runIntegrationTests-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-runIntegrationTests-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            gradle-runIntegrationTests-
            gradle-
      - name: Integration Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew -i runIntegrationTests
